
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AnimatedCounter: typeof import("../../src/components/AnimatedCounter.vue")['default']
  BackToTop: typeof import("../../src/components/BackToTop.vue")['default']
  Footer: typeof import("../../src/components/Footer.vue")['default']
  MediaLoader: typeof import("../../src/components/MediaLoader.vue")['default']
  Navbar: typeof import("../../src/components/Navbar.vue")['default']
  RdLogo: typeof import("../../src/components/RdLogo.vue")['default']
  SectionHeader: typeof import("../../src/components/SectionHeader.vue")['default']
  ThemeToggle: typeof import("../../src/components/ThemeToggle.vue")['default']
  Container: typeof import("../../src/components/layout/Container.vue")['default']
  Section: typeof import("../../src/components/layout/Section.vue")['default']
  Button: typeof import("../../src/components/ui/Button.vue")['default']
  Card: typeof import("../../src/components/ui/Card.vue")['default']
  AboutBio: typeof import("../../src/features/about/AboutBio.vue")['default']
  AboutSkills: typeof import("../../src/features/about/AboutSkills.vue")['default']
  AboutSlider: typeof import("../../src/features/about/AboutSlider.vue")['default']
  AboutTimeline: typeof import("../../src/features/about/AboutTimeline.vue")['default']
  ContactForm: typeof import("../../src/features/contact/ContactForm.vue")['default']
  ContactInfo: typeof import("../../src/features/contact/ContactInfo.vue")['default']
  GalleryCard: typeof import("../../src/features/gallery/GalleryCard.vue")['default']
  GalleryLightbox: typeof import("../../src/features/gallery/GalleryLightbox.vue")['default']
  HeroScene3D: typeof import("../../src/features/home/HeroScene3D.vue")['default']
  HeroSceneGalaxy: typeof import("../../src/features/home/HeroSceneGalaxy.vue")['default']
  HeroSceneModel: typeof import("../../src/features/home/HeroSceneModel.vue")['default']
  HomeCapabilities: typeof import("../../src/features/home/HomeCapabilities.vue")['default']
  HomeHero: typeof import("../../src/features/home/HomeHero.vue")['default']
  HomeServices: typeof import("../../src/features/home/HomeServices.vue")['default']
  HomeShowcaseBanner: typeof import("../../src/features/home/HomeShowcaseBanner.vue")['default']
  HomeStats: typeof import("../../src/features/home/HomeStats.vue")['default']
  ProjectCard: typeof import("../../src/features/projects/ProjectCard.vue")['default']
  ProjectsGrid: typeof import("../../src/features/projects/ProjectsGrid.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  AccumulativeShadows: typeof import("@tresjs/cientos")['AccumulativeShadows']
  Align: typeof import("@tresjs/cientos")['Align']
  AnimatedSprite: typeof import("@tresjs/cientos")['AnimatedSprite']
  Backdrop: typeof import("@tresjs/cientos")['Backdrop']
  BakeShadows: typeof import("@tresjs/cientos")['BakeShadows']
  BaseCameraControls: typeof import("@tresjs/cientos")['BaseCameraControls']
  Billboard: typeof import("@tresjs/cientos")['Billboard']
  Bounds: typeof import("@tresjs/cientos")['Bounds']
  Box: typeof import("@tresjs/cientos")['Box']
  CameraControls: typeof import("@tresjs/cientos")['CameraControls']
  CameraShake: typeof import("@tresjs/cientos")['CameraShake']
  CatmullRomCurve3: typeof import("@tresjs/cientos")['CatmullRomCurve3']
  Circle: typeof import("@tresjs/cientos")['Circle']
  CircleShadow: typeof import("@tresjs/cientos")['CircleShadow']
  Cone: typeof import("@tresjs/cientos")['Cone']
  ContactShadows: typeof import("@tresjs/cientos")['ContactShadows']
  CubeCamera: typeof import("@tresjs/cientos")['CubeCamera']
  CubicBezierLine: typeof import("@tresjs/cientos")['CubicBezierLine']
  CustomShaderMaterial: typeof import("@tresjs/cientos")['CustomShaderMaterial']
  Cylinder: typeof import("@tresjs/cientos")['Cylinder']
  Decal: typeof import("@tresjs/cientos")['Decal']
  DecalDebugUI: typeof import("@tresjs/cientos")['DecalDebugUI']
  Dodecahedron: typeof import("@tresjs/cientos")['Dodecahedron']
  Edges: typeof import("@tresjs/cientos")['Edges']
  Environment: typeof import("@tresjs/cientos")['Environment']
  FBXModel: typeof import("@tresjs/cientos")['FBXModel']
  Fbo: typeof import("@tresjs/cientos")['Fbo']
  Fit: typeof import("@tresjs/cientos")['Fit']
  GLTFModel: typeof import("@tresjs/cientos")['GLTFModel']
  GlobalAudio: typeof import("@tresjs/cientos")['GlobalAudio']
  GradientTexture: typeof import("@tresjs/cientos")['GradientTexture']
  Grid: typeof import("@tresjs/cientos")['Grid']
  Helper: typeof import("@tresjs/cientos")['Helper']
  HolographicMaterial: typeof import("@tresjs/cientos")['HolographicMaterial']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Icosahedron: typeof import("@tresjs/cientos")['Icosahedron']
  Image: typeof import("@tresjs/cientos")['Image']
  KeyboardControls: typeof import("@tresjs/cientos")['KeyboardControls']
  LOD: typeof import("@tresjs/cientos")['LOD']
  Lensflare: typeof import("@tresjs/cientos")['Lensflare']
  Levioso: typeof import("@tresjs/cientos")['Levioso']
  Lightformer: typeof import("@tresjs/cientos")['Lightformer']
  Line2: typeof import("@tresjs/cientos")['Line2']
  MapControls: typeof import("@tresjs/cientos")['MapControls']
  MarchingCube: typeof import("@tresjs/cientos")['MarchingCube']
  MarchingCubes: typeof import("@tresjs/cientos")['MarchingCubes']
  MarchingPlane: typeof import("@tresjs/cientos")['MarchingPlane']
  Mask: typeof import("@tresjs/cientos")['Mask']
  MeshDiscardMaterial: typeof import("@tresjs/cientos")['MeshDiscardMaterial']
  MeshGlassMaterial: typeof import("@tresjs/cientos")['MeshGlassMaterial']
  MeshReflectionMaterial: typeof import("@tresjs/cientos")['MeshReflectionMaterial']
  MeshTransmissionMaterial: typeof import("@tresjs/cientos")['MeshTransmissionMaterial']
  MeshWobbleMaterial: typeof import("@tresjs/cientos")['MeshWobbleMaterial']
  MouseParallax: typeof import("@tresjs/cientos")['MouseParallax']
  Ocean: typeof import("@tresjs/cientos")['Ocean']
  Octahedron: typeof import("@tresjs/cientos")['Octahedron']
  OrbitControls: typeof import("@tresjs/cientos")['OrbitControls']
  Outline: typeof import("@tresjs/cientos")['Outline']
  Plane: typeof import("@tresjs/cientos")['Plane']
  PointMaterial: typeof import("@tresjs/cientos")['PointMaterial']
  PointerLockControls: typeof import("@tresjs/cientos")['PointerLockControls']
  PositionalAudio: typeof import("@tresjs/cientos")['PositionalAudio']
  Precipitation: typeof import("@tresjs/cientos")['Precipitation']
  QuadraticBezierLine: typeof import("@tresjs/cientos")['QuadraticBezierLine']
  RandomizedLights: typeof import("@tresjs/cientos")['RandomizedLights']
  Reflector: typeof import("@tresjs/cientos")['Reflector']
  Ring: typeof import("@tresjs/cientos")['Ring']
  RoundedBox: typeof import("@tresjs/cientos")['RoundedBox']
  Sampler: typeof import("@tresjs/cientos")['Sampler']
  ScreenQuad: typeof import("@tresjs/cientos")['ScreenQuad']
  ScreenSizer: typeof import("@tresjs/cientos")['ScreenSizer']
  ScreenSpace: typeof import("@tresjs/cientos")['ScreenSpace']
  ScrollControls: typeof import("@tresjs/cientos")['ScrollControls']
  Sky: typeof import("@tresjs/cientos")['Sky']
  Smoke: typeof import("@tresjs/cientos")['Smoke']
  SoftShadows: typeof import("@tresjs/cientos")['SoftShadows']
  Sparkles: typeof import("@tresjs/cientos")['Sparkles']
  Sphere: typeof import("@tresjs/cientos")['Sphere']
  Stage: typeof import("@tresjs/cientos")['Stage']
  Stars: typeof import("@tresjs/cientos")['Stars']
  Stats: typeof import("@tresjs/cientos")['Stats']
  StatsGl: typeof import("@tresjs/cientos")['StatsGl']
  Superformula: typeof import("@tresjs/cientos")['Superformula']
  Tetrahedron: typeof import("@tresjs/cientos")['Tetrahedron']
  Text3D: typeof import("@tresjs/cientos")['Text3D']
  Torus: typeof import("@tresjs/cientos")['Torus']
  TorusKnot: typeof import("@tresjs/cientos")['TorusKnot']
  TransformControls: typeof import("@tresjs/cientos")['TransformControls']
  Tube: typeof import("@tresjs/cientos")['Tube']
  UseSVG: typeof import("@tresjs/cientos")['UseSVG']
  UseTexture: typeof import("@tresjs/cientos")['UseTexture']
  TresCanvas: typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
  TresCanvas: typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAnimatedCounter: LazyComponent<typeof import("../../src/components/AnimatedCounter.vue")['default']>
  LazyBackToTop: LazyComponent<typeof import("../../src/components/BackToTop.vue")['default']>
  LazyFooter: LazyComponent<typeof import("../../src/components/Footer.vue")['default']>
  LazyMediaLoader: LazyComponent<typeof import("../../src/components/MediaLoader.vue")['default']>
  LazyNavbar: LazyComponent<typeof import("../../src/components/Navbar.vue")['default']>
  LazyRdLogo: LazyComponent<typeof import("../../src/components/RdLogo.vue")['default']>
  LazySectionHeader: LazyComponent<typeof import("../../src/components/SectionHeader.vue")['default']>
  LazyThemeToggle: LazyComponent<typeof import("../../src/components/ThemeToggle.vue")['default']>
  LazyContainer: LazyComponent<typeof import("../../src/components/layout/Container.vue")['default']>
  LazySection: LazyComponent<typeof import("../../src/components/layout/Section.vue")['default']>
  LazyButton: LazyComponent<typeof import("../../src/components/ui/Button.vue")['default']>
  LazyCard: LazyComponent<typeof import("../../src/components/ui/Card.vue")['default']>
  LazyAboutBio: LazyComponent<typeof import("../../src/features/about/AboutBio.vue")['default']>
  LazyAboutSkills: LazyComponent<typeof import("../../src/features/about/AboutSkills.vue")['default']>
  LazyAboutSlider: LazyComponent<typeof import("../../src/features/about/AboutSlider.vue")['default']>
  LazyAboutTimeline: LazyComponent<typeof import("../../src/features/about/AboutTimeline.vue")['default']>
  LazyContactForm: LazyComponent<typeof import("../../src/features/contact/ContactForm.vue")['default']>
  LazyContactInfo: LazyComponent<typeof import("../../src/features/contact/ContactInfo.vue")['default']>
  LazyGalleryCard: LazyComponent<typeof import("../../src/features/gallery/GalleryCard.vue")['default']>
  LazyGalleryLightbox: LazyComponent<typeof import("../../src/features/gallery/GalleryLightbox.vue")['default']>
  LazyHeroScene3D: LazyComponent<typeof import("../../src/features/home/HeroScene3D.vue")['default']>
  LazyHeroSceneGalaxy: LazyComponent<typeof import("../../src/features/home/HeroSceneGalaxy.vue")['default']>
  LazyHeroSceneModel: LazyComponent<typeof import("../../src/features/home/HeroSceneModel.vue")['default']>
  LazyHomeCapabilities: LazyComponent<typeof import("../../src/features/home/HomeCapabilities.vue")['default']>
  LazyHomeHero: LazyComponent<typeof import("../../src/features/home/HomeHero.vue")['default']>
  LazyHomeServices: LazyComponent<typeof import("../../src/features/home/HomeServices.vue")['default']>
  LazyHomeShowcaseBanner: LazyComponent<typeof import("../../src/features/home/HomeShowcaseBanner.vue")['default']>
  LazyHomeStats: LazyComponent<typeof import("../../src/features/home/HomeStats.vue")['default']>
  LazyProjectCard: LazyComponent<typeof import("../../src/features/projects/ProjectCard.vue")['default']>
  LazyProjectsGrid: LazyComponent<typeof import("../../src/features/projects/ProjectsGrid.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyAccumulativeShadows: LazyComponent<typeof import("@tresjs/cientos")['AccumulativeShadows']>
  LazyAlign: LazyComponent<typeof import("@tresjs/cientos")['Align']>
  LazyAnimatedSprite: LazyComponent<typeof import("@tresjs/cientos")['AnimatedSprite']>
  LazyBackdrop: LazyComponent<typeof import("@tresjs/cientos")['Backdrop']>
  LazyBakeShadows: LazyComponent<typeof import("@tresjs/cientos")['BakeShadows']>
  LazyBaseCameraControls: LazyComponent<typeof import("@tresjs/cientos")['BaseCameraControls']>
  LazyBillboard: LazyComponent<typeof import("@tresjs/cientos")['Billboard']>
  LazyBounds: LazyComponent<typeof import("@tresjs/cientos")['Bounds']>
  LazyBox: LazyComponent<typeof import("@tresjs/cientos")['Box']>
  LazyCameraControls: LazyComponent<typeof import("@tresjs/cientos")['CameraControls']>
  LazyCameraShake: LazyComponent<typeof import("@tresjs/cientos")['CameraShake']>
  LazyCatmullRomCurve3: LazyComponent<typeof import("@tresjs/cientos")['CatmullRomCurve3']>
  LazyCircle: LazyComponent<typeof import("@tresjs/cientos")['Circle']>
  LazyCircleShadow: LazyComponent<typeof import("@tresjs/cientos")['CircleShadow']>
  LazyCone: LazyComponent<typeof import("@tresjs/cientos")['Cone']>
  LazyContactShadows: LazyComponent<typeof import("@tresjs/cientos")['ContactShadows']>
  LazyCubeCamera: LazyComponent<typeof import("@tresjs/cientos")['CubeCamera']>
  LazyCubicBezierLine: LazyComponent<typeof import("@tresjs/cientos")['CubicBezierLine']>
  LazyCustomShaderMaterial: LazyComponent<typeof import("@tresjs/cientos")['CustomShaderMaterial']>
  LazyCylinder: LazyComponent<typeof import("@tresjs/cientos")['Cylinder']>
  LazyDecal: LazyComponent<typeof import("@tresjs/cientos")['Decal']>
  LazyDecalDebugUI: LazyComponent<typeof import("@tresjs/cientos")['DecalDebugUI']>
  LazyDodecahedron: LazyComponent<typeof import("@tresjs/cientos")['Dodecahedron']>
  LazyEdges: LazyComponent<typeof import("@tresjs/cientos")['Edges']>
  LazyEnvironment: LazyComponent<typeof import("@tresjs/cientos")['Environment']>
  LazyFBXModel: LazyComponent<typeof import("@tresjs/cientos")['FBXModel']>
  LazyFbo: LazyComponent<typeof import("@tresjs/cientos")['Fbo']>
  LazyFit: LazyComponent<typeof import("@tresjs/cientos")['Fit']>
  LazyGLTFModel: LazyComponent<typeof import("@tresjs/cientos")['GLTFModel']>
  LazyGlobalAudio: LazyComponent<typeof import("@tresjs/cientos")['GlobalAudio']>
  LazyGradientTexture: LazyComponent<typeof import("@tresjs/cientos")['GradientTexture']>
  LazyGrid: LazyComponent<typeof import("@tresjs/cientos")['Grid']>
  LazyHelper: LazyComponent<typeof import("@tresjs/cientos")['Helper']>
  LazyHolographicMaterial: LazyComponent<typeof import("@tresjs/cientos")['HolographicMaterial']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyIcosahedron: LazyComponent<typeof import("@tresjs/cientos")['Icosahedron']>
  LazyImage: LazyComponent<typeof import("@tresjs/cientos")['Image']>
  LazyKeyboardControls: LazyComponent<typeof import("@tresjs/cientos")['KeyboardControls']>
  LazyLOD: LazyComponent<typeof import("@tresjs/cientos")['LOD']>
  LazyLensflare: LazyComponent<typeof import("@tresjs/cientos")['Lensflare']>
  LazyLevioso: LazyComponent<typeof import("@tresjs/cientos")['Levioso']>
  LazyLightformer: LazyComponent<typeof import("@tresjs/cientos")['Lightformer']>
  LazyLine2: LazyComponent<typeof import("@tresjs/cientos")['Line2']>
  LazyMapControls: LazyComponent<typeof import("@tresjs/cientos")['MapControls']>
  LazyMarchingCube: LazyComponent<typeof import("@tresjs/cientos")['MarchingCube']>
  LazyMarchingCubes: LazyComponent<typeof import("@tresjs/cientos")['MarchingCubes']>
  LazyMarchingPlane: LazyComponent<typeof import("@tresjs/cientos")['MarchingPlane']>
  LazyMask: LazyComponent<typeof import("@tresjs/cientos")['Mask']>
  LazyMeshDiscardMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshDiscardMaterial']>
  LazyMeshGlassMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshGlassMaterial']>
  LazyMeshReflectionMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshReflectionMaterial']>
  LazyMeshTransmissionMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshTransmissionMaterial']>
  LazyMeshWobbleMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshWobbleMaterial']>
  LazyMouseParallax: LazyComponent<typeof import("@tresjs/cientos")['MouseParallax']>
  LazyOcean: LazyComponent<typeof import("@tresjs/cientos")['Ocean']>
  LazyOctahedron: LazyComponent<typeof import("@tresjs/cientos")['Octahedron']>
  LazyOrbitControls: LazyComponent<typeof import("@tresjs/cientos")['OrbitControls']>
  LazyOutline: LazyComponent<typeof import("@tresjs/cientos")['Outline']>
  LazyPlane: LazyComponent<typeof import("@tresjs/cientos")['Plane']>
  LazyPointMaterial: LazyComponent<typeof import("@tresjs/cientos")['PointMaterial']>
  LazyPointerLockControls: LazyComponent<typeof import("@tresjs/cientos")['PointerLockControls']>
  LazyPositionalAudio: LazyComponent<typeof import("@tresjs/cientos")['PositionalAudio']>
  LazyPrecipitation: LazyComponent<typeof import("@tresjs/cientos")['Precipitation']>
  LazyQuadraticBezierLine: LazyComponent<typeof import("@tresjs/cientos")['QuadraticBezierLine']>
  LazyRandomizedLights: LazyComponent<typeof import("@tresjs/cientos")['RandomizedLights']>
  LazyReflector: LazyComponent<typeof import("@tresjs/cientos")['Reflector']>
  LazyRing: LazyComponent<typeof import("@tresjs/cientos")['Ring']>
  LazyRoundedBox: LazyComponent<typeof import("@tresjs/cientos")['RoundedBox']>
  LazySampler: LazyComponent<typeof import("@tresjs/cientos")['Sampler']>
  LazyScreenQuad: LazyComponent<typeof import("@tresjs/cientos")['ScreenQuad']>
  LazyScreenSizer: LazyComponent<typeof import("@tresjs/cientos")['ScreenSizer']>
  LazyScreenSpace: LazyComponent<typeof import("@tresjs/cientos")['ScreenSpace']>
  LazyScrollControls: LazyComponent<typeof import("@tresjs/cientos")['ScrollControls']>
  LazySky: LazyComponent<typeof import("@tresjs/cientos")['Sky']>
  LazySmoke: LazyComponent<typeof import("@tresjs/cientos")['Smoke']>
  LazySoftShadows: LazyComponent<typeof import("@tresjs/cientos")['SoftShadows']>
  LazySparkles: LazyComponent<typeof import("@tresjs/cientos")['Sparkles']>
  LazySphere: LazyComponent<typeof import("@tresjs/cientos")['Sphere']>
  LazyStage: LazyComponent<typeof import("@tresjs/cientos")['Stage']>
  LazyStars: LazyComponent<typeof import("@tresjs/cientos")['Stars']>
  LazyStats: LazyComponent<typeof import("@tresjs/cientos")['Stats']>
  LazyStatsGl: LazyComponent<typeof import("@tresjs/cientos")['StatsGl']>
  LazySuperformula: LazyComponent<typeof import("@tresjs/cientos")['Superformula']>
  LazyTetrahedron: LazyComponent<typeof import("@tresjs/cientos")['Tetrahedron']>
  LazyText3D: LazyComponent<typeof import("@tresjs/cientos")['Text3D']>
  LazyTorus: LazyComponent<typeof import("@tresjs/cientos")['Torus']>
  LazyTorusKnot: LazyComponent<typeof import("@tresjs/cientos")['TorusKnot']>
  LazyTransformControls: LazyComponent<typeof import("@tresjs/cientos")['TransformControls']>
  LazyTube: LazyComponent<typeof import("@tresjs/cientos")['Tube']>
  LazyUseSVG: LazyComponent<typeof import("@tresjs/cientos")['UseSVG']>
  LazyUseTexture: LazyComponent<typeof import("@tresjs/cientos")['UseTexture']>
  LazyTresCanvas: LazyComponent<typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']>
  LazyTresCanvas: LazyComponent<typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
