// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/21/2026, 11:26:32 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/WEB/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/features/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/plugins/**/*.{js,ts,mjs}","D:/WEB/src/composables/**/*.{js,ts,mjs}","D:/WEB/src/utils/**/*.{js,ts,mjs}","D:/WEB/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/WEB/src/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;