
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AnimatedCounter: typeof import("../src/components/AnimatedCounter.vue")['default']
export const BackToTop: typeof import("../src/components/BackToTop.vue")['default']
export const Footer: typeof import("../src/components/Footer.vue")['default']
export const MediaLoader: typeof import("../src/components/MediaLoader.vue")['default']
export const Navbar: typeof import("../src/components/Navbar.vue")['default']
export const RdLogo: typeof import("../src/components/RdLogo.vue")['default']
export const SectionHeader: typeof import("../src/components/SectionHeader.vue")['default']
export const ThemeToggle: typeof import("../src/components/ThemeToggle.vue")['default']
export const Container: typeof import("../src/components/layout/Container.vue")['default']
export const Section: typeof import("../src/components/layout/Section.vue")['default']
export const Button: typeof import("../src/components/ui/Button.vue")['default']
export const Card: typeof import("../src/components/ui/Card.vue")['default']
export const AboutBio: typeof import("../src/features/about/AboutBio.vue")['default']
export const AboutSkills: typeof import("../src/features/about/AboutSkills.vue")['default']
export const AboutSlider: typeof import("../src/features/about/AboutSlider.vue")['default']
export const AboutTimeline: typeof import("../src/features/about/AboutTimeline.vue")['default']
export const ContactForm: typeof import("../src/features/contact/ContactForm.vue")['default']
export const ContactInfo: typeof import("../src/features/contact/ContactInfo.vue")['default']
export const GalleryCard: typeof import("../src/features/gallery/GalleryCard.vue")['default']
export const GalleryLightbox: typeof import("../src/features/gallery/GalleryLightbox.vue")['default']
export const HeroScene3D: typeof import("../src/features/home/HeroScene3D.vue")['default']
export const HeroSceneGalaxy: typeof import("../src/features/home/HeroSceneGalaxy.vue")['default']
export const HeroSceneModel: typeof import("../src/features/home/HeroSceneModel.vue")['default']
export const HomeCapabilities: typeof import("../src/features/home/HomeCapabilities.vue")['default']
export const HomeHero: typeof import("../src/features/home/HomeHero.vue")['default']
export const HomeServices: typeof import("../src/features/home/HomeServices.vue")['default']
export const HomeShowcaseBanner: typeof import("../src/features/home/HomeShowcaseBanner.vue")['default']
export const HomeStats: typeof import("../src/features/home/HomeStats.vue")['default']
export const ProjectCard: typeof import("../src/features/projects/ProjectCard.vue")['default']
export const ProjectsGrid: typeof import("../src/features/projects/ProjectsGrid.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AccumulativeShadows: typeof import("@tresjs/cientos")['AccumulativeShadows']
export const Align: typeof import("@tresjs/cientos")['Align']
export const AnimatedSprite: typeof import("@tresjs/cientos")['AnimatedSprite']
export const Backdrop: typeof import("@tresjs/cientos")['Backdrop']
export const BakeShadows: typeof import("@tresjs/cientos")['BakeShadows']
export const BaseCameraControls: typeof import("@tresjs/cientos")['BaseCameraControls']
export const Billboard: typeof import("@tresjs/cientos")['Billboard']
export const Bounds: typeof import("@tresjs/cientos")['Bounds']
export const Box: typeof import("@tresjs/cientos")['Box']
export const CameraControls: typeof import("@tresjs/cientos")['CameraControls']
export const CameraShake: typeof import("@tresjs/cientos")['CameraShake']
export const CatmullRomCurve3: typeof import("@tresjs/cientos")['CatmullRomCurve3']
export const Circle: typeof import("@tresjs/cientos")['Circle']
export const CircleShadow: typeof import("@tresjs/cientos")['CircleShadow']
export const Cone: typeof import("@tresjs/cientos")['Cone']
export const ContactShadows: typeof import("@tresjs/cientos")['ContactShadows']
export const CubeCamera: typeof import("@tresjs/cientos")['CubeCamera']
export const CubicBezierLine: typeof import("@tresjs/cientos")['CubicBezierLine']
export const CustomShaderMaterial: typeof import("@tresjs/cientos")['CustomShaderMaterial']
export const Cylinder: typeof import("@tresjs/cientos")['Cylinder']
export const Decal: typeof import("@tresjs/cientos")['Decal']
export const DecalDebugUI: typeof import("@tresjs/cientos")['DecalDebugUI']
export const Dodecahedron: typeof import("@tresjs/cientos")['Dodecahedron']
export const Edges: typeof import("@tresjs/cientos")['Edges']
export const Environment: typeof import("@tresjs/cientos")['Environment']
export const FBXModel: typeof import("@tresjs/cientos")['FBXModel']
export const Fbo: typeof import("@tresjs/cientos")['Fbo']
export const Fit: typeof import("@tresjs/cientos")['Fit']
export const GLTFModel: typeof import("@tresjs/cientos")['GLTFModel']
export const GlobalAudio: typeof import("@tresjs/cientos")['GlobalAudio']
export const GradientTexture: typeof import("@tresjs/cientos")['GradientTexture']
export const Grid: typeof import("@tresjs/cientos")['Grid']
export const Helper: typeof import("@tresjs/cientos")['Helper']
export const HolographicMaterial: typeof import("@tresjs/cientos")['HolographicMaterial']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Icosahedron: typeof import("@tresjs/cientos")['Icosahedron']
export const Image: typeof import("@tresjs/cientos")['Image']
export const KeyboardControls: typeof import("@tresjs/cientos")['KeyboardControls']
export const LOD: typeof import("@tresjs/cientos")['LOD']
export const Lensflare: typeof import("@tresjs/cientos")['Lensflare']
export const Levioso: typeof import("@tresjs/cientos")['Levioso']
export const Lightformer: typeof import("@tresjs/cientos")['Lightformer']
export const Line2: typeof import("@tresjs/cientos")['Line2']
export const MapControls: typeof import("@tresjs/cientos")['MapControls']
export const MarchingCube: typeof import("@tresjs/cientos")['MarchingCube']
export const MarchingCubes: typeof import("@tresjs/cientos")['MarchingCubes']
export const MarchingPlane: typeof import("@tresjs/cientos")['MarchingPlane']
export const Mask: typeof import("@tresjs/cientos")['Mask']
export const MeshDiscardMaterial: typeof import("@tresjs/cientos")['MeshDiscardMaterial']
export const MeshGlassMaterial: typeof import("@tresjs/cientos")['MeshGlassMaterial']
export const MeshReflectionMaterial: typeof import("@tresjs/cientos")['MeshReflectionMaterial']
export const MeshTransmissionMaterial: typeof import("@tresjs/cientos")['MeshTransmissionMaterial']
export const MeshWobbleMaterial: typeof import("@tresjs/cientos")['MeshWobbleMaterial']
export const MouseParallax: typeof import("@tresjs/cientos")['MouseParallax']
export const Ocean: typeof import("@tresjs/cientos")['Ocean']
export const Octahedron: typeof import("@tresjs/cientos")['Octahedron']
export const OrbitControls: typeof import("@tresjs/cientos")['OrbitControls']
export const Outline: typeof import("@tresjs/cientos")['Outline']
export const Plane: typeof import("@tresjs/cientos")['Plane']
export const PointMaterial: typeof import("@tresjs/cientos")['PointMaterial']
export const PointerLockControls: typeof import("@tresjs/cientos")['PointerLockControls']
export const PositionalAudio: typeof import("@tresjs/cientos")['PositionalAudio']
export const Precipitation: typeof import("@tresjs/cientos")['Precipitation']
export const QuadraticBezierLine: typeof import("@tresjs/cientos")['QuadraticBezierLine']
export const RandomizedLights: typeof import("@tresjs/cientos")['RandomizedLights']
export const Reflector: typeof import("@tresjs/cientos")['Reflector']
export const Ring: typeof import("@tresjs/cientos")['Ring']
export const RoundedBox: typeof import("@tresjs/cientos")['RoundedBox']
export const Sampler: typeof import("@tresjs/cientos")['Sampler']
export const ScreenQuad: typeof import("@tresjs/cientos")['ScreenQuad']
export const ScreenSizer: typeof import("@tresjs/cientos")['ScreenSizer']
export const ScreenSpace: typeof import("@tresjs/cientos")['ScreenSpace']
export const ScrollControls: typeof import("@tresjs/cientos")['ScrollControls']
export const Sky: typeof import("@tresjs/cientos")['Sky']
export const Smoke: typeof import("@tresjs/cientos")['Smoke']
export const SoftShadows: typeof import("@tresjs/cientos")['SoftShadows']
export const Sparkles: typeof import("@tresjs/cientos")['Sparkles']
export const Sphere: typeof import("@tresjs/cientos")['Sphere']
export const Stage: typeof import("@tresjs/cientos")['Stage']
export const Stars: typeof import("@tresjs/cientos")['Stars']
export const Stats: typeof import("@tresjs/cientos")['Stats']
export const StatsGl: typeof import("@tresjs/cientos")['StatsGl']
export const Superformula: typeof import("@tresjs/cientos")['Superformula']
export const Tetrahedron: typeof import("@tresjs/cientos")['Tetrahedron']
export const Text3D: typeof import("@tresjs/cientos")['Text3D']
export const Torus: typeof import("@tresjs/cientos")['Torus']
export const TorusKnot: typeof import("@tresjs/cientos")['TorusKnot']
export const TransformControls: typeof import("@tresjs/cientos")['TransformControls']
export const Tube: typeof import("@tresjs/cientos")['Tube']
export const UseSVG: typeof import("@tresjs/cientos")['UseSVG']
export const UseTexture: typeof import("@tresjs/cientos")['UseTexture']
export const TresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const TresCanvas: typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAnimatedCounter: LazyComponent<typeof import("../src/components/AnimatedCounter.vue")['default']>
export const LazyBackToTop: LazyComponent<typeof import("../src/components/BackToTop.vue")['default']>
export const LazyFooter: LazyComponent<typeof import("../src/components/Footer.vue")['default']>
export const LazyMediaLoader: LazyComponent<typeof import("../src/components/MediaLoader.vue")['default']>
export const LazyNavbar: LazyComponent<typeof import("../src/components/Navbar.vue")['default']>
export const LazyRdLogo: LazyComponent<typeof import("../src/components/RdLogo.vue")['default']>
export const LazySectionHeader: LazyComponent<typeof import("../src/components/SectionHeader.vue")['default']>
export const LazyThemeToggle: LazyComponent<typeof import("../src/components/ThemeToggle.vue")['default']>
export const LazyContainer: LazyComponent<typeof import("../src/components/layout/Container.vue")['default']>
export const LazySection: LazyComponent<typeof import("../src/components/layout/Section.vue")['default']>
export const LazyButton: LazyComponent<typeof import("../src/components/ui/Button.vue")['default']>
export const LazyCard: LazyComponent<typeof import("../src/components/ui/Card.vue")['default']>
export const LazyAboutBio: LazyComponent<typeof import("../src/features/about/AboutBio.vue")['default']>
export const LazyAboutSkills: LazyComponent<typeof import("../src/features/about/AboutSkills.vue")['default']>
export const LazyAboutSlider: LazyComponent<typeof import("../src/features/about/AboutSlider.vue")['default']>
export const LazyAboutTimeline: LazyComponent<typeof import("../src/features/about/AboutTimeline.vue")['default']>
export const LazyContactForm: LazyComponent<typeof import("../src/features/contact/ContactForm.vue")['default']>
export const LazyContactInfo: LazyComponent<typeof import("../src/features/contact/ContactInfo.vue")['default']>
export const LazyGalleryCard: LazyComponent<typeof import("../src/features/gallery/GalleryCard.vue")['default']>
export const LazyGalleryLightbox: LazyComponent<typeof import("../src/features/gallery/GalleryLightbox.vue")['default']>
export const LazyHeroScene3D: LazyComponent<typeof import("../src/features/home/HeroScene3D.vue")['default']>
export const LazyHeroSceneGalaxy: LazyComponent<typeof import("../src/features/home/HeroSceneGalaxy.vue")['default']>
export const LazyHeroSceneModel: LazyComponent<typeof import("../src/features/home/HeroSceneModel.vue")['default']>
export const LazyHomeCapabilities: LazyComponent<typeof import("../src/features/home/HomeCapabilities.vue")['default']>
export const LazyHomeHero: LazyComponent<typeof import("../src/features/home/HomeHero.vue")['default']>
export const LazyHomeServices: LazyComponent<typeof import("../src/features/home/HomeServices.vue")['default']>
export const LazyHomeShowcaseBanner: LazyComponent<typeof import("../src/features/home/HomeShowcaseBanner.vue")['default']>
export const LazyHomeStats: LazyComponent<typeof import("../src/features/home/HomeStats.vue")['default']>
export const LazyProjectCard: LazyComponent<typeof import("../src/features/projects/ProjectCard.vue")['default']>
export const LazyProjectsGrid: LazyComponent<typeof import("../src/features/projects/ProjectsGrid.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAccumulativeShadows: LazyComponent<typeof import("@tresjs/cientos")['AccumulativeShadows']>
export const LazyAlign: LazyComponent<typeof import("@tresjs/cientos")['Align']>
export const LazyAnimatedSprite: LazyComponent<typeof import("@tresjs/cientos")['AnimatedSprite']>
export const LazyBackdrop: LazyComponent<typeof import("@tresjs/cientos")['Backdrop']>
export const LazyBakeShadows: LazyComponent<typeof import("@tresjs/cientos")['BakeShadows']>
export const LazyBaseCameraControls: LazyComponent<typeof import("@tresjs/cientos")['BaseCameraControls']>
export const LazyBillboard: LazyComponent<typeof import("@tresjs/cientos")['Billboard']>
export const LazyBounds: LazyComponent<typeof import("@tresjs/cientos")['Bounds']>
export const LazyBox: LazyComponent<typeof import("@tresjs/cientos")['Box']>
export const LazyCameraControls: LazyComponent<typeof import("@tresjs/cientos")['CameraControls']>
export const LazyCameraShake: LazyComponent<typeof import("@tresjs/cientos")['CameraShake']>
export const LazyCatmullRomCurve3: LazyComponent<typeof import("@tresjs/cientos")['CatmullRomCurve3']>
export const LazyCircle: LazyComponent<typeof import("@tresjs/cientos")['Circle']>
export const LazyCircleShadow: LazyComponent<typeof import("@tresjs/cientos")['CircleShadow']>
export const LazyCone: LazyComponent<typeof import("@tresjs/cientos")['Cone']>
export const LazyContactShadows: LazyComponent<typeof import("@tresjs/cientos")['ContactShadows']>
export const LazyCubeCamera: LazyComponent<typeof import("@tresjs/cientos")['CubeCamera']>
export const LazyCubicBezierLine: LazyComponent<typeof import("@tresjs/cientos")['CubicBezierLine']>
export const LazyCustomShaderMaterial: LazyComponent<typeof import("@tresjs/cientos")['CustomShaderMaterial']>
export const LazyCylinder: LazyComponent<typeof import("@tresjs/cientos")['Cylinder']>
export const LazyDecal: LazyComponent<typeof import("@tresjs/cientos")['Decal']>
export const LazyDecalDebugUI: LazyComponent<typeof import("@tresjs/cientos")['DecalDebugUI']>
export const LazyDodecahedron: LazyComponent<typeof import("@tresjs/cientos")['Dodecahedron']>
export const LazyEdges: LazyComponent<typeof import("@tresjs/cientos")['Edges']>
export const LazyEnvironment: LazyComponent<typeof import("@tresjs/cientos")['Environment']>
export const LazyFBXModel: LazyComponent<typeof import("@tresjs/cientos")['FBXModel']>
export const LazyFbo: LazyComponent<typeof import("@tresjs/cientos")['Fbo']>
export const LazyFit: LazyComponent<typeof import("@tresjs/cientos")['Fit']>
export const LazyGLTFModel: LazyComponent<typeof import("@tresjs/cientos")['GLTFModel']>
export const LazyGlobalAudio: LazyComponent<typeof import("@tresjs/cientos")['GlobalAudio']>
export const LazyGradientTexture: LazyComponent<typeof import("@tresjs/cientos")['GradientTexture']>
export const LazyGrid: LazyComponent<typeof import("@tresjs/cientos")['Grid']>
export const LazyHelper: LazyComponent<typeof import("@tresjs/cientos")['Helper']>
export const LazyHolographicMaterial: LazyComponent<typeof import("@tresjs/cientos")['HolographicMaterial']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyIcosahedron: LazyComponent<typeof import("@tresjs/cientos")['Icosahedron']>
export const LazyImage: LazyComponent<typeof import("@tresjs/cientos")['Image']>
export const LazyKeyboardControls: LazyComponent<typeof import("@tresjs/cientos")['KeyboardControls']>
export const LazyLOD: LazyComponent<typeof import("@tresjs/cientos")['LOD']>
export const LazyLensflare: LazyComponent<typeof import("@tresjs/cientos")['Lensflare']>
export const LazyLevioso: LazyComponent<typeof import("@tresjs/cientos")['Levioso']>
export const LazyLightformer: LazyComponent<typeof import("@tresjs/cientos")['Lightformer']>
export const LazyLine2: LazyComponent<typeof import("@tresjs/cientos")['Line2']>
export const LazyMapControls: LazyComponent<typeof import("@tresjs/cientos")['MapControls']>
export const LazyMarchingCube: LazyComponent<typeof import("@tresjs/cientos")['MarchingCube']>
export const LazyMarchingCubes: LazyComponent<typeof import("@tresjs/cientos")['MarchingCubes']>
export const LazyMarchingPlane: LazyComponent<typeof import("@tresjs/cientos")['MarchingPlane']>
export const LazyMask: LazyComponent<typeof import("@tresjs/cientos")['Mask']>
export const LazyMeshDiscardMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshDiscardMaterial']>
export const LazyMeshGlassMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshGlassMaterial']>
export const LazyMeshReflectionMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshReflectionMaterial']>
export const LazyMeshTransmissionMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshTransmissionMaterial']>
export const LazyMeshWobbleMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshWobbleMaterial']>
export const LazyMouseParallax: LazyComponent<typeof import("@tresjs/cientos")['MouseParallax']>
export const LazyOcean: LazyComponent<typeof import("@tresjs/cientos")['Ocean']>
export const LazyOctahedron: LazyComponent<typeof import("@tresjs/cientos")['Octahedron']>
export const LazyOrbitControls: LazyComponent<typeof import("@tresjs/cientos")['OrbitControls']>
export const LazyOutline: LazyComponent<typeof import("@tresjs/cientos")['Outline']>
export const LazyPlane: LazyComponent<typeof import("@tresjs/cientos")['Plane']>
export const LazyPointMaterial: LazyComponent<typeof import("@tresjs/cientos")['PointMaterial']>
export const LazyPointerLockControls: LazyComponent<typeof import("@tresjs/cientos")['PointerLockControls']>
export const LazyPositionalAudio: LazyComponent<typeof import("@tresjs/cientos")['PositionalAudio']>
export const LazyPrecipitation: LazyComponent<typeof import("@tresjs/cientos")['Precipitation']>
export const LazyQuadraticBezierLine: LazyComponent<typeof import("@tresjs/cientos")['QuadraticBezierLine']>
export const LazyRandomizedLights: LazyComponent<typeof import("@tresjs/cientos")['RandomizedLights']>
export const LazyReflector: LazyComponent<typeof import("@tresjs/cientos")['Reflector']>
export const LazyRing: LazyComponent<typeof import("@tresjs/cientos")['Ring']>
export const LazyRoundedBox: LazyComponent<typeof import("@tresjs/cientos")['RoundedBox']>
export const LazySampler: LazyComponent<typeof import("@tresjs/cientos")['Sampler']>
export const LazyScreenQuad: LazyComponent<typeof import("@tresjs/cientos")['ScreenQuad']>
export const LazyScreenSizer: LazyComponent<typeof import("@tresjs/cientos")['ScreenSizer']>
export const LazyScreenSpace: LazyComponent<typeof import("@tresjs/cientos")['ScreenSpace']>
export const LazyScrollControls: LazyComponent<typeof import("@tresjs/cientos")['ScrollControls']>
export const LazySky: LazyComponent<typeof import("@tresjs/cientos")['Sky']>
export const LazySmoke: LazyComponent<typeof import("@tresjs/cientos")['Smoke']>
export const LazySoftShadows: LazyComponent<typeof import("@tresjs/cientos")['SoftShadows']>
export const LazySparkles: LazyComponent<typeof import("@tresjs/cientos")['Sparkles']>
export const LazySphere: LazyComponent<typeof import("@tresjs/cientos")['Sphere']>
export const LazyStage: LazyComponent<typeof import("@tresjs/cientos")['Stage']>
export const LazyStars: LazyComponent<typeof import("@tresjs/cientos")['Stars']>
export const LazyStats: LazyComponent<typeof import("@tresjs/cientos")['Stats']>
export const LazyStatsGl: LazyComponent<typeof import("@tresjs/cientos")['StatsGl']>
export const LazySuperformula: LazyComponent<typeof import("@tresjs/cientos")['Superformula']>
export const LazyTetrahedron: LazyComponent<typeof import("@tresjs/cientos")['Tetrahedron']>
export const LazyText3D: LazyComponent<typeof import("@tresjs/cientos")['Text3D']>
export const LazyTorus: LazyComponent<typeof import("@tresjs/cientos")['Torus']>
export const LazyTorusKnot: LazyComponent<typeof import("@tresjs/cientos")['TorusKnot']>
export const LazyTransformControls: LazyComponent<typeof import("@tresjs/cientos")['TransformControls']>
export const LazyTube: LazyComponent<typeof import("@tresjs/cientos")['Tube']>
export const LazyUseSVG: LazyComponent<typeof import("@tresjs/cientos")['UseSVG']>
export const LazyUseTexture: LazyComponent<typeof import("@tresjs/cientos")['UseTexture']>
export const LazyTresCanvas: LazyComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']>
export const LazyTresCanvas: LazyComponent<typeof import("../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
